version: '3.9'
services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-12.8}
    profiles: ['prod', 'db']
    container_name: postgres
    # restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-'123456'}
    # you can disable exposing ports to host if there is only docker-compose services need to access postgres
    ports:
      - '5432:${POSTGRES_PORT:-5432}'
    volumes:
      - ${POSTGRES_DATA:-/var/mira/data}:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - mira
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    profiles: ['prod', 'qbt']
    container_name: qbittorrent
    environment:
      PUID: 1000
      PGID: 1000
      WEBUI_PORT: ${QBT_HTTP_PORT:-8091}
    ports:
      - '6881:${QB_TCP_PORT:-6881}'
      - '6881:${QBT_UDP_PORT:-6881}/udp'
      - '8091:${QBT_HTTP_PORT:-8091}'
    restart: unless-stopped
    volumes:
      - ${QBT_DOWNLOADS_LOCATION:-/data/downloads}:/downloads
      - ${QBT_CONFIG_LOCATION:-./qb/qbittorrent}:/config
    networks:
      - mira
  picfit:
    image: 'picfit-local'
    profiles: ['picfit', 'prod']
    environment:
      PICFIT_CONFIG_PATH: /etc/picfit/config.json
    volumes:
      - {PICFIT_CONFIG:-./picfit/config.json}:/etc/picfit/config.json:ro
  nginx:
    image: nginx:1.19
    profiles: ['prod', 'nginx']
    volumes:
      - ${NGINX_CONFIG:-./nginx/nginx.conf}:/etc/nginx/nginx.conf:ro
      - ${DOWNLOAD_DATA:-/data/albireo/}:/home/wwwroot/albireo:ro
      - ${NGINX_DENEB:-./web/}:/home/wwwroot/mira:ro
    restart: always
    networks:
      - mira

networks:
  mira:
    external: true
    name: mira