version: '3.9'
services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-12.8}
    profiles: ['prod', 'db']
    container_name: postgres
    # restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-'123456'}
    # you can disable exposing ports to host if there is only docker-compose services need to access postgres
#    ports:
#      - '5432:${POSTGRES_PORT:-5432}'
    volumes:
      - ${POSTGRES_DATA:-/var/mira/data}:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - mira
    logging:
      driver: json-file
      options:
        max_size: '10m'
        max_file: '5'
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    profiles: ['prod', 'qbt']
    container_name: qbittorrent
    environment:
      PUID: 0
      PGID: 0
      WEBUI_PORT: ${QBT_HTTP_PORT:-8091}
    ports:
      - '6881:${QB_TCP_PORT:-6881}'
      - '6881:${QBT_UDP_PORT:-6881}/udp'
      #- '8091:${QBT_HTTP_PORT:-8091}'
    restart: unless-stopped
    volumes:
      - ${DOWNLOAD_DATA:-/data/albireo}:/data/download
      - ${QBT_CONFIG_LOCATION:-./qb/qbittorrent}:/config
    networks:
      - mira
    logging:
      driver: json-file
      options:
        max_size: '10m'
        max_file: '5'
  picfit:
    image: mira/picfit
    profiles: ['picfit', 'prod']
    environment:
      PICFIT_CONFIG_PATH: /etc/picfit/config.json
    volumes:
      - ${DOWNLOAD_DATA:-/data/albireo}:/data/albireo
      - ${PICFIT_CONFIG:-./picfit/config.json}:/etc/picfit/config.json:ro
    restart: always
    networks:
      - mira
    logging:
      driver: json-file
      options:
        max_size: '10m'
        max_file: '5'
  nginx:
    image: nginx:1.19
    profiles: ['prod', 'nginx']
    #ports:
    #  - '80:80'
    volumes:
      - ${NGINX_CONFIG:-./nginx/nginx.conf}:/etc/nginx/nginx.conf:ro
      - ${DOWNLOAD_DATA:-/data/albireo}:/home/wwwroot/albireo:ro
      - ${NGINX_DENEB:-./web}:/home/wwwroot/mira
    restart: always
    depends_on:
      - picfit
    networks:
      - mira
      - local
    logging:
      driver: json-file
      options:
        max_size: '10m'
        max_file: '5'
  rabbitmq:
    image: rabbitmq:3-management
    profiles: [ 'prod', 'rabbitmq' ]
    container_name: rabbitmq
    hostname: ${RABBITMQ_HOSTNAME:-quark_mq}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST:-/}
    ports:
     - '${RABBITMQ_MANAGEMENT_PORT:-15672}:15672'
    volumes:
      - ${RABBITMQ_DATA:-./rabbitmq/data}:/var/lib/rabbitmq:rw
      - ${RABBITMQ_CONFIG:-./rabbitmq/config/rabbitmq.config}:/etc/rabbitmq/rabbitmq.config:rw
    restart: always
    networks:
      - mira
    logging:
      driver: json-file
      options:
        max_size: '10m'
        max_file: '5'
networks:
  local:
    external: true
    name: networks_local
  mira:
    external: true
    name: mira